## Data cleaning

In [341]:
import pandas as pd

%store -r data_frame
%store -r list_of_columns
%store -r missing_values_above_80_percent
%store -r missing_values_below_10_percent 

#remove limit displaying rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

### Delete columns and rows with missing values.

Removal of columns with more than 80% missing values.

In [342]:
data_frame = data_frame.drop(columns=missing_values_above_80_percent)
data_frame.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,20220914061546,2022-09-14,city scrape,Hyde Park - Walk to UChicago,You are invited to be the sole Airbnb guest in...,The apartment is less than one block from beau...,https://a0.muscache.com/pictures/acf6b3c0-47f2...,2613,https://www.airbnb.com/users/show/2613,Rebecca,2008-08-29,"Chicago, IL",My 2 bdrm apartment is a 2nd floor walk-up in ...,within an hour,100%,97%,t,https://a0.muscache.com/im/pictures/user/8bb47...,https://a0.muscache.com/im/pictures/user/8bb47...,Hyde Park,1,1,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Hyde Park,41.787900,-87.587800,Private room in condo,Private room,1,1 shared bath,1.0,1.0,"[""Hot water kettle"", ""Conditioner"", ""Heating"",...",$110.00,3,89,3,3,1125,1125,3.0,1125.0,t,13,25,50,320,2022-09-14,207,19,2,2015-01-09,2022-09-09,4.99,4.98,4.99,4.99,4.99,4.96,4.94,R17000015609,t,1,0,1,0,2.21
1,7126,https://www.airbnb.com/rooms/7126,20220914061546,2022-09-14,city scrape,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhoo...,"Ukrainian Village was just named ""Hottest Neig...",https://a0.muscache.com/pictures/51073/16c81c7...,17928,https://www.airbnb.com/users/show/17928,Sarah,2009-05-19,"Chicago, IL",We live in Chicago. We love to travel and see ...,within an hour,100%,96%,t,https://a0.muscache.com/im/users/17928/profile...,https://a0.muscache.com/im/users/17928/profile...,Ukrainian Village,2,2,"['email', 'phone']",t,t,"Chicago, Illinois, United States",West Town,41.901660,-87.680210,Entire rental unit,Entire home/apt,2,1 bath,1.0,1.0,"[""Room-darkening shades"", ""Hot water kettle"", ...",$91.00,2,60,2,2,1125,1125,2.0,1125.0,t,11,22,52,320,2022-09-14,459,51,2,2009-07-03,2022-08-28,4.68,4.84,4.56,4.90,4.87,4.88,4.74,R21000075737,f,1,1,0,0,2.86
2,10945,https://www.airbnb.com/rooms/10945,20220914061546,2022-09-14,city scrape,The Biddle House (#1),Beautiful first floor apartment in Historic Ol...,NaN,https://a0.muscache.com/pictures/58d1a420-a24b...,33004,https://www.airbnb.com/users/show/33004,At Home Inn,2009-08-21,"Chicago, IL","Hi, we're Bob and Liz Biddle, long time Chicag...",within an hour,100%,99%,t,https://a0.muscache.com/im/pictures/user/e23d4...,https://a0.muscache.com/im/pictures/user/e23d4...,Old Town,9,82,"['email', 'phone', 'work_email']",t,t,NaN,Lincoln Park,41.911960,-87.639810,Entire rental unit,Entire home/apt,4,1 bath,2.0,2.0,"[""Washer"", ""Patio or balcony"", ""Heating"", ""Pri...",$157.00,4,180,3,4,1125,1125,4.0,1125.0,t,4,23,47,137,2022-09-14,56,23,2,2014-04-28,2022-08-23,4.63,4.73,4.80,4.79,4.77,4.98,4.64,2209984,t,9,9,0,0,0.55
3,12140,https://www.airbnb.com/rooms/12140,20220914061546,2022-09-14,city scrape,Lincoln Park Guest House,Bed and Breakfast license issued by the City o...,The Guest House is in the heart of Chicago's m...,https://a0.muscache.com/pictures/55126/6a4f01b...,46734,https://www.airbnb.com/users/show/46734,Sharon And Robert,2009-10-18,"Chicago, IL",Best in the city with long-time urban-dwelling...,within an hour,100%,89%,f,https://a0.muscache.com/im/users/46734/profile...,https://a0.muscache.com/im/users/46734/profile...,Lincoln Park,1,1,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Lincoln Park,41.923570,-87.649470,Room in boutique hotel,Private room,3,1 private bath,1.0,1.0,"[""Heating"", ""Free parking on premises"", ""Hot w...",$329.00,2,7,2,2,7,7,2.0,7.0,t,21,45,75,165,2022-09-14,13,6,2,2015-06-29,2022-09-12,5.00,5.00,5.00,5.00,5.00,5.00,4.85,R20000055258,f,1,0,1,0,0.15
4,24833,https://www.airbnb.com/rooms/24833,20220914061546,2022-09-14,city scrape,Prime LincolnPark 1 Block Fullerton Express L ...,Perfect private entrance apartment one block f...,Lincoln Park is a great neighborhood where peo...,https://a0.muscache.com/pictures/ac17be6f-40bd...,101521,https://www.airbnb.com/users/show/101521,Red,2010-03-31,"Chicago, IL",Travel is fun and exciting but can be hard on ...,within a few hours,90%,77%,f,https://a0.muscache.com/im/users/101521/profil...,https://a0.muscache.com/im/users/101521/profil...,Lincoln Park,8,12,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Lincoln Park,41.925961,-87.656364,Entire rental unit,Entire home/apt,3,1 bath,1.0,1.0,"[""Room-darkening shades"", ""HDTV with standard ...",$86.00,32,395,32,32,395,395,32.0,395.0,t,0,1,31,306,2022-09-14,40,2,0,2010-05-24,2022-04-23,4.28,4.04,3.93,4.14,3.96,4.89,4.18,City registration pending,f,3,3,0,0,0.27

Removal of blank rows in columns where the missing value was less than 10%

In [343]:
data_frame = data_frame.dropna(subset=missing_values_below_10_percent)

In [344]:
data_frame.shape

(5722, 72)

After removing the missing data, 5722 rows and 72 columns remain.

In [345]:
data_frame.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,5.722000e+03,5.722000e+03,5.722000e+03,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5.722000e+03,5722.000000,5.722000e+03,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,5722.000000,4788.00000,4786.000000,4786.000000,4786.000000,4785.000000,4786.000000,4786.000000,5722.000000,5722.000000,5722.000000,5722.000000,4788.00000
mean,1.823850e+17,2.022091e+13,1.507197e+08,300.825061,338.379588,41.893914,-87.663783,4.519923,1.875393,2.349528,13.328207,648.540196,14.832226,63.054002,822.465921,3.378606e+06,60.974956,2.636483e+06,11.461028,30.198357,51.967669,212.767913,47.402307,15.163404,1.467494,4.73292,4.786862,4.726617,4.851022,4.840401,4.753147,4.674624,44.840615,42.736631,1.822964,0.169346,2.06250
std,2.888265e+17,0.000000e+00,1.437020e+08,1033.410992,1139.895562,0.062039,0.044977,3.071889,1.139014,1.784929,43.400135,475.750359,54.337958,188.154185,447.104026,8.510854e+07,182.296170,6.824100e+07,9.333101,19.331332,28.867650,125.569926,84.781915,26.909029,2.163499,0.40312,0.373791,0.406048,0.322084,0.349553,0.394254,0.419011,132.387493,132.899398,5.574238,1.463230,1.92258
min,2.384000e+03,2.022091e+13,2.153000e+03,1.000000,1.000000,41.650640,-87.901560,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000e+00,1.000000,2.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.01000
25%,2.987785e+07,2.022091e+13,2.800625e+07,1.000000,2.000000,41.863507,-87.687792,2.000000,1.000000,1.000000,2.000000,149.250000,2.000000,2.000000,365.000000,3.650000e+02,2.000000,3.650000e+02,3.000000,13.000000,32.000000,86.000000,2.000000,1.000000,0.000000,4.67000,4.750000,4.640000,4.830000,4.830000,4.690000,4.600000,1.000000,1.000000,0.000000,0.000000,0.67000
50%,4.786159e+07,2.022091e+13,1.074344e+08,4.000000,6.000000,41.897823,-87.659170,4.000000,2.000000,2.000000,2.000000,365.000000,2.000000,3.000000,1125.000000,1.125000e+03,2.800000,1.125000e+03,10.000000,33.000000,60.000000,243.000000,15.000000,7.000000,1.000000,4.84000,4.890000,4.850000,4.950000,4.950000,4.880000,4.780000,4.000000,2.000000,0.000000,0.000000,1.71000
75%,5.718707e+17,2.022091e+13,2.430356e+08,18.000000,27.000000,41.938038,-87.631996,6.000000,2.000000,3.000000,32.000000,1125.000000,32.000000,32.000000,1125.000000,1.125000e+03,32.000000,1.125000e+03,19.000000,47.000000,75.750000,335.000000,56.000000,23.000000,2.000000,4.97000,5.000000,4.980000,5.000000,5.000000,4.990000,4.900000,14.000000,9.000000,1.000000,0.000000,3.00000
max,7.149113e+17,2.022091e+13,4.778108e+08,4050.000000,6605.000000,42.033620,-87.534090,16.000000,12.000000,20.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,2.147484e+09,1125.000000,2.118332e+09,30.000000,60.000000,90.000000,365.000000,2600.000000,1284.000000,68.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,525.000000,525.000000,49.000000,18.000000,55.71000

In [346]:
data_frame.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,20220914061546,2022-09-14,city scrape,Hyde Park - Walk to UChicago,You are invited to be the sole Airbnb guest in...,The apartment is less than one block from beau...,https://a0.muscache.com/pictures/acf6b3c0-47f2...,2613,https://www.airbnb.com/users/show/2613,Rebecca,2008-08-29,"Chicago, IL",My 2 bdrm apartment is a 2nd floor walk-up in ...,within an hour,100%,97%,t,https://a0.muscache.com/im/pictures/user/8bb47...,https://a0.muscache.com/im/pictures/user/8bb47...,Hyde Park,1,1,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Hyde Park,41.787900,-87.587800,Private room in condo,Private room,1,1 shared bath,1.0,1.0,"[""Hot water kettle"", ""Conditioner"", ""Heating"",...",$110.00,3,89,3,3,1125,1125,3.0,1125.0,t,13,25,50,320,2022-09-14,207,19,2,2015-01-09,2022-09-09,4.99,4.98,4.99,4.99,4.99,4.96,4.94,R17000015609,t,1,0,1,0,2.21
1,7126,https://www.airbnb.com/rooms/7126,20220914061546,2022-09-14,city scrape,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhoo...,"Ukrainian Village was just named ""Hottest Neig...",https://a0.muscache.com/pictures/51073/16c81c7...,17928,https://www.airbnb.com/users/show/17928,Sarah,2009-05-19,"Chicago, IL",We live in Chicago. We love to travel and see ...,within an hour,100%,96%,t,https://a0.muscache.com/im/users/17928/profile...,https://a0.muscache.com/im/users/17928/profile...,Ukrainian Village,2,2,"['email', 'phone']",t,t,"Chicago, Illinois, United States",West Town,41.901660,-87.680210,Entire rental unit,Entire home/apt,2,1 bath,1.0,1.0,"[""Room-darkening shades"", ""Hot water kettle"", ...",$91.00,2,60,2,2,1125,1125,2.0,1125.0,t,11,22,52,320,2022-09-14,459,51,2,2009-07-03,2022-08-28,4.68,4.84,4.56,4.90,4.87,4.88,4.74,R21000075737,f,1,1,0,0,2.86
2,10945,https://www.airbnb.com/rooms/10945,20220914061546,2022-09-14,city scrape,The Biddle House (#1),Beautiful first floor apartment in Historic Ol...,NaN,https://a0.muscache.com/pictures/58d1a420-a24b...,33004,https://www.airbnb.com/users/show/33004,At Home Inn,2009-08-21,"Chicago, IL","Hi, we're Bob and Liz Biddle, long time Chicag...",within an hour,100%,99%,t,https://a0.muscache.com/im/pictures/user/e23d4...,https://a0.muscache.com/im/pictures/user/e23d4...,Old Town,9,82,"['email', 'phone', 'work_email']",t,t,NaN,Lincoln Park,41.911960,-87.639810,Entire rental unit,Entire home/apt,4,1 bath,2.0,2.0,"[""Washer"", ""Patio or balcony"", ""Heating"", ""Pri...",$157.00,4,180,3,4,1125,1125,4.0,1125.0,t,4,23,47,137,2022-09-14,56,23,2,2014-04-28,2022-08-23,4.63,4.73,4.80,4.79,4.77,4.98,4.64,2209984,t,9,9,0,0,0.55
3,12140,https://www.airbnb.com/rooms/12140,20220914061546,2022-09-14,city scrape,Lincoln Park Guest House,Bed and Breakfast license issued by the City o...,The Guest House is in the heart of Chicago's m...,https://a0.muscache.com/pictures/55126/6a4f01b...,46734,https://www.airbnb.com/users/show/46734,Sharon And Robert,2009-10-18,"Chicago, IL",Best in the city with long-time urban-dwelling...,within an hour,100%,89%,f,https://a0.muscache.com/im/users/46734/profile...,https://a0.muscache.com/im/users/46734/profile...,Lincoln Park,1,1,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Lincoln Park,41.923570,-87.649470,Room in boutique hotel,Private room,3,1 private bath,1.0,1.0,"[""Heating"", ""Free parking on premises"", ""Hot w...",$329.00,2,7,2,2,7,7,2.0,7.0,t,21,45,75,165,2022-09-14,13,6,2,2015-06-29,2022-09-12,5.00,5.00,5.00,5.00,5.00,5.00,4.85,R20000055258,f,1,0,1,0,0.15
4,24833,https://www.airbnb.com/rooms/24833,20220914061546,2022-09-14,city scrape,Prime LincolnPark 1 Block Fullerton Express L ...,Perfect private entrance apartment one block f...,Lincoln Park is a great neighborhood where peo...,https://a0.muscache.com/pictures/ac17be6f-40bd...,101521,https://www.airbnb.com/users/show/101521,Red,2010-03-31,"Chicago, IL",Travel is fun and exciting but can be hard on ...,within a few hours,90%,77%,f,https://a0.muscache.com/im/users/101521/profil...,https://a0.muscache.com/im/users/101521/profil...,Lincoln Park,8,12,"['email', 'phone']",t,t,"Chicago, Illinois, United States",Lincoln Park,41.925961,-87.656364,Entire rental unit,Entire home/apt,3,1 bath,1.0,1.0,"[""Room-darkening shades"", ""HDTV with standard ...",$86.00,32,395,32,32,395,395,32.0,395.0,t,0,1,31,306,2022-09-14,40,2,0,2010-05-24,2022-04-23,4.28,4.04,3.93,4.14,3.96,4.89,4.18,City registration pending,f,3,3,0,0,0.27

Updating lists of columns of a given type after deleting NaN values

In [347]:
int_columns = [*data_frame.select_dtypes(include=['int'])]
float_columns = [*data_frame.select_dtypes(include=['float'])]
object_columns = [*data_frame.select_dtypes(include=['object'])]

### Verify that all columns have the correct types

In [348]:
data_frame[['host_response_rate','price','host_acceptance_rate']].head()

  host_response_rate    price host_acceptance_rate
0               100%  $110.00                  97%
1               100%   $91.00                  96%
2               100%  $157.00                  99%
3               100%  $329.00                  89%
4                90%   $86.00                  77%

In [349]:
'host_response_rate' in object_columns, 'price' in object_columns, 'host_acceptance_rate' in object_columns

(True, True, True)

The above columns should be cleared of "%" and $ signs, because they were incorrectly qualified as 'object'

In [350]:
data_frame.price = data_frame.price.apply(lambda x: x.replace('$',''))
data_frame.price = data_frame.price.apply(lambda x: x.replace(',',''))
data_frame.price = pd.to_numeric(data_frame.price, errors='coerce')
data_frame.price.describe()

count     5722.000000
mean       219.076896
std        278.169271
min         18.000000
25%         96.000000
50%        156.000000
75%        249.000000
max      10000.000000
Name: price, dtype: float64

The 'price' column has been cleaned up and its type changed to float64

In [351]:
data_frame.host_response_rate = data_frame.host_response_rate.str.replace('%','')
data_frame.host_response_rate = data_frame.host_response_rate.astype(float)/100

data_frame.host_acceptance_rate = data_frame.host_acceptance_rate.str.replace('%','')
data_frame.host_acceptance_rate = data_frame.host_acceptance_rate.astype(float)/100

In [352]:
data_frame[['host_response_rate','price','host_acceptance_rate']].dtypes

host_response_rate      float64
price                   float64
host_acceptance_rate    float64
dtype: object

Removed the '%' signs and changed the other two columns to float, reflecting percentages to decimals

### Check where there are still missing values:

In [353]:
missing_values = {}

def missing_values_check(columns_to_check):
    #check if missing values dcit is empty
    missing_values.clear()
    
    for index in columns_to_check:
        if data_frame[index].isna().sum() > 0:
            missing_values[index] = data_frame[index].isna().sum()
    
    if len(missing_values) == 0:
        print ('There are no missing values ​​in the following columns:' + f"{columns_to_check}")
    else:
        print(missing_values)

missing_values_check(object_columns)

{'neighborhood_overview': 1723, 'host_location': 842, 'host_about': 1769, 'host_response_time': 191, 'host_response_rate': 191, 'neighbourhood': 1723, 'first_review': 934, 'last_review': 934, 'license': 756}

In [354]:
missing_values_col_indexes = list(missing_values.keys())
data_frame[missing_values_col_indexes].dtypes

neighborhood_overview     object
host_location             object
host_about                object
host_response_time        object
host_response_rate       float64
neighbourhood             object
first_review              object
last_review               object
license                   object
dtype: object

Missing values ​​should be supplemented, e.g. with average values ​​or the most numerous categorical ones

In [355]:
data_frame[missing_values_col_indexes].head()

,neighborhood_overview,host_location,host_about,host_response_time,host_response_rate,neighbourhood,first_review,last_review,license
0,The apartment is less than one block from beau...,"Chicago, IL",My 2 bdrm apartment is a 2nd floor walk-up in ...,within an hour,1.0,"Chicago, Illinois, United States",2015-01-09,2022-09-09,R17000015609
1,"Ukrainian Village was just named ""Hottest Neig...","Chicago, IL",We live in Chicago. We love to travel and see ...,within an hour,1.0,"Chicago, Illinois, United States",2009-07-03,2022-08-28,R21000075737
2,NaN,"Chicago, IL","Hi, we're Bob and Liz Biddle, long time Chicag...",within an hour,1.0,NaN,2014-04-28,2022-08-23,2209984
3,The Guest House is in the heart of Chicago's m...,"Chicago, IL",Best in the city with long-time urban-dwelling...,within an hour,1.0,"Chicago, Illinois, United States",2015-06-29,2022-09-12,R20000055258
4,Lincoln Park is a great neighborhood where peo...,"Chicago, IL",Travel is fun and exciting but can be hard on ...,within a few hours,0.9,"Chicago, Illinois, United States",2010-05-24,2022-04-23,City registration pending

Most of the missing values ​​are contained in the 'object' type. Columns: host_location, host_response_time, neighborhood, will be filled with the most numerous categories. The host_response_rate column will be filled with an average value. In the remaining columns we will replace NaN with the string 'no info'. From the point of view of further analysis, the missing description 'host_about' will probably not be a problem, but it will be disadvantageous for us to remove 1769 records including NaN for this reason.

In [356]:
to_fill_list = ['host_location', 'host_response_time', 'neighbourhood']

A function that fills the columns in the list above with the most common values:

In [357]:
def fill_missing(col_name):
    result = data_frame.groupby(col_name)[col_name].count().rename('count')
    result_df = pd.DataFrame(result)
    result_df = result_df.reset_index().sort_values(by=['count'],ascending=False)
    to_fill = result_df[col_name].iloc[0]
    data_frame[col_name] = data_frame[col_name].fillna(value=to_fill)
    
for col in to_fill_list:
    fill_missing(col)

Checking if columns containing NaN values ​​have been completed:

In [361]:

missing_values_check(to_fill_list)

There are no missing values ​​in the following columns:['host_location', 'host_response_time', 'neighbourhood']

In [365]:
data_frame.host_acceptance_rate.mean()

0.9124379587556799

Poszukujemy odstających wartości

In [359]:
data_frame.accommodates.max(), data_frame.accommodates.mean()

(16, 4.519923103809857)

Usuwamy odstające wartości

Sprawdzamy gdzie jeszcze mamy nany i uzupełniamy wartościami średnimi lub najliczniejszymi kategoriami

Jak nie ma nanów tworzymy rozkład normalny dla int i float, pewnie jeszcze raz bierzemy float